// app/components/ui/Modal.vue
<template>
 <Teleport to="body">
 <Transition name="modal">
 <div v-if="modelValue" class="fixed inset-0 z-[100] flex items-center justify-center">
 <div class="fixed inset-0 bg-slate-900/50 backdrop-blur-sm transition-opacity" @click="$emit('update:modelValue', false)"></div>
 
 <div class="relative bg-white rounded-3xl p-6 w-full max-w-md mx-4 shadow-2xl transform transition-all">
 <div class="flex items-start justify-between mb-4">
 <h3 class="text-xl text-slate-800">{{ title }}</h3>
 <button @click="$emit('update:modelValue', false)" class="text-slate-400 hover:text-slate-600 transition-colors">
 <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
 </button>
 </div>
 
 <div class="text-slate-600 mb-6">
 <slot></slot>
 </div>
 
 <div class="flex items-center gap-3 justify-end">
 <button @click="$emit('update:modelValue', false)" class="px-5 py-2.5 rounded-xl text-sm text-slate-700 bg-slate-100 hover:bg-slate-200 transition-colors">
 Cancel
 </button>
 <button @click="$emit('confirm')" class="px-5 py-2.5 rounded-xl text-sm text-white bg-emerald-600 hover:bg-emerald-700 transition-colors">
 Confirm
 </button>
 </div>
 </div>
 </div>
 </Transition>
 </Teleport>
</template>

<script setup>
defineProps({
 modelValue: {
 type: Boolean,
 required: true
 },
 title: {
 type: String,
 default: 'Confirm Action'
 }
});
defineEmits(['update:modelValue', 'confirm']);
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
 transition: all 0.2s ease;
}
.modal-enter-from,
.modal-leave-to {
 opacity: 0;
}
.modal-enter-from .relative,
.modal-leave-to .relative {
 transform: scale(0.95) translateY(10px);
}
</style>

// app/components/ui/Modal.tsx
"use client";

import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';

export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm?: () => void;
  title?: string;
  children?: React.ReactNode;
}

export default function Modal({
  isOpen,
  onClose,
  onConfirm,
  title = 'Confirm Action',
  children
}: ModalProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;
  if (!isOpen) return null;

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center">
      <div 
        className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />
      
      <div className="relative bg-white rounded-3xl p-6 w-full max-w-md mx-4 shadow-2xl transform transition-all animate-modal-in">
        <div className="flex items-start justify-between mb-4">
          <h3 className="text-xl text-slate-800">{title}</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>
        </div>
        
        <div className="text-slate-600 mb-6">
          {children}
        </div>
        
        <div className="flex items-center gap-3 justify-end">
          <button onClick={onClose} className="px-5 py-2.5 rounded-xl text-sm text-slate-700 bg-slate-100 hover:bg-slate-200 transition-colors">
            Cancel
          </button>
          <button onClick={onConfirm} className="px-5 py-2.5 rounded-xl text-sm text-white bg-emerald-600 hover:bg-emerald-700 transition-colors">
            Confirm
          </button>
        </div>
      </div>
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes modal-in {
          from {
            opacity: 0;
            transform: scale(0.95) translateY(10px);
          }
          to {
            opacity: 1;
            transform: scale(1) translateY(0);
          }
        }
        .animate-modal-in {
          animation: modal-in 0.2s ease;
        }
      `}} />
    </div>,
    document.body
  );
}
