// app/pages/reset-password.vue
<template>
  <div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-slate-50">
    <div class="max-w-[420px] w-full">
      <div class="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
        <!-- Logo placeholder -->
         <div class="mx-auto rounded-lg flex items-center justify-center mb-6">
          <img src="@/assets/img/logo.png" class="h-6 w-auto" />
        </div>
        
        <h2 class="text-2xl font-semibold text-slate-900 text-left">Create a new password</h2>
        <p class="mt-2 text-sm text-slate-500 text-left mb-6">Choose a new password for name@moneyfieldmfb.com</p>

        <form class="space-y-4 text-left" @submit.prevent="handleReset">
          <AuthInput
            v-model="password"
            label="New password"
            type="password"
            placeholder="!@#$%^&*(password)"
            required
          />
          <AuthInput
            v-model="confirmPassword"
            label="Confirm new password"
            type="password"
            placeholder="!@#$%^&*(password)"
            required
          />
          
          <div class="flex flex-wrap gap-2 mt-4">
            <span :class="pillClass(hasMinLength)">At least 8 characters</span>
            <span :class="pillClass(hasUpper)">One uppercase letter</span>
            <span :class="pillClass(hasLower)">One lowercase letter</span>
            <span :class="pillClass(hasNumber)">One number</span>
            <span :class="pillClass(hasSymbol)">One symbol</span>
          </div>
          
          <button type="submit" class="w-full mt-6 py-3 px-4 rounded-xl text-white font-medium bg-emerald-500 hover:bg-emerald-600 transition-colors">
            Reset password
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { useToast } from '@/composables/useToast';

definePageMeta({
  layout: false
});

const router = useRouter();
const { addToast } = useToast();
const password = ref('');
const confirmPassword = ref('');

const hasMinLength = computed(() => password.value.length >= 8);
const hasUpper = computed(() => /[A-Z]/.test(password.value));
const hasLower = computed(() => /[a-z]/.test(password.value));
const hasNumber = computed(() => /[0-9]/.test(password.value));
const hasSymbol = computed(() => /[^A-Za-z0-9]/.test(password.value));

const pillClass = (isValid) => {
  if (isValid) {
    return 'px-2.5 py-1 bg-emerald-50 text-emerald-700 text-[11px] font-medium rounded-full transition-colors';
  }
  return 'px-2.5 py-1 bg-slate-50 text-slate-500 text-[11px] font-medium rounded-full transition-colors';
};

const handleReset = () => {
  if (password.value !== confirmPassword.value) {
    addToast("Passwords do not match", 'error');
    return;
  }
  router.push('/password-reset-success');
};
</script>

// app/reset-password/page.tsx
"use client";

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { useToast } from '@/app/composables/useToast';
import AuthInput from '@/app/components/Auth/Input';

export default function ResetPasswordPage() {
  const router = useRouter();
  const { addToast } = useToast();
  
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');

  const hasMinLength = useMemo(() => password.length >= 8, [password]);
  const hasUpper = useMemo(() => /[A-Z]/.test(password), [password]);
  const hasLower = useMemo(() => /[a-z]/.test(password), [password]);
  const hasNumber = useMemo(() => /[0-9]/.test(password), [password]);
  const hasSymbol = useMemo(() => /[^A-Za-z0-9]/.test(password), [password]);

  const getPillClass = (isValid: boolean) => {
    if (isValid) {
      return 'px-2.5 py-1 bg-emerald-50 text-emerald-700 text-[11px] font-medium rounded-full transition-colors';
    }
    return 'px-2.5 py-1 bg-slate-50 text-slate-500 text-[11px] font-medium rounded-full transition-colors';
  };

  const handleReset = (e: React.FormEvent) => {
    e.preventDefault();
    if (password !== confirmPassword) {
      addToast("Passwords do not match", 'error');
      return;
    }
    router.push('/password-reset-success');
  };

  return (
    <div className="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-slate-50">
      <div className="max-w-[420px] w-full">
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
          {/* Logo placeholder */}
          <div className="mx-auto rounded-lg flex items-center justify-center mb-6">
            <img src="/logo.png" className="h-8 w-auto" alt="Logo" />
          </div>
          
          <h2 className="text-2xl font-semibold text-slate-900 text-left">Create a new password</h2>
          <p className="mt-2 text-sm text-slate-500 text-left mb-6">Choose a new password for name@moneyfieldmfb.com</p>

          <form className="space-y-4 text-left" onSubmit={handleReset}>
            <AuthInput
              value={password}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
              label="New password"
              type="password"
              placeholder="!@#$%^&*(password)"
              required
            />
            <AuthInput
              value={confirmPassword}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setConfirmPassword(e.target.value)}
              label="Confirm new password"
              type="password"
              placeholder="!@#$%^&*(password)"
              required
            />
            
            <div className="flex flex-wrap gap-2 mt-4">
              <span className={getPillClass(hasMinLength)}>At least 8 characters</span>
              <span className={getPillClass(hasUpper)}>One uppercase letter</span>
              <span className={getPillClass(hasLower)}>One lowercase letter</span>
              <span className={getPillClass(hasNumber)}>One number</span>
              <span className={getPillClass(hasSymbol)}>One symbol</span>
            </div>
            
            <button type="submit" className="w-full mt-6 py-3 px-4 rounded-xl text-white font-medium bg-emerald-500 hover:bg-emerald-600 transition-colors">
              Reset password
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
